### ISSUE TITLE
Main Flow Bug

### ISSUE THREAD

**Issue by svechkuzavas** [TheAlisher/NavigationFlowSample#1]
[Демонстрация](https://drive.google.com/file/d/1BF9Oj5CmSw_H1sbXw-tV0O4tUxwxuJIp/view?usp=sharing)

**Comment by abalta** [comment]
same bug for me, I'll fix it, just replace in menu_bottom_navigation.xml file

use

navigation_home with first item id

instead of

navigation_dashboard

**Comment by TheAlisher** [comment]
yep, it's my mistake, i didn't notice it )
