### ISSUE TITLE
How set  SupportActionBar  & appBarConfiguration for toolbar press back (android.R.id.home)

### ISSUE THREAD

**Issue by CMingTseng** [TheAlisher/NavigationFlowSample#3]
Dear Sir

i fork the demo & modify it 

https://github.com/TheAlisher/NavigationFlowSample/commit/0919cccc2ff3338a23b9fd7ce7897047749e7806

i need toolbar   for  back action 

but  press  toolbar back (android.R.id.home) 

it not work 

can teach me ?

THX

![image](https://user-images.githubusercontent.com/7948140/193469565-d4bb2185-afd0-4349-bfc4-453029019948.png)

**Comment by TheAlisher** [comment]
You can just add this code block

```
class MainFlowFragment : BaseFlowFragment(
    R.layout.flow_fragment_main, R.id.nav_host_fragment_main
) {

    private val binding by viewBinding(FlowFragmentMainBinding::bind)

    override fun setupNavigation() {
        binding.toolbar.setupWithNavController(
            navController, AppBarConfiguration(navController.graph)
        )
    }
}
```
